"""
Pre-populated lists of string items for use in populating fake data using lambda functions
"""


fake_data_lorem = [
    "Lorem ipsum dolor sit amet",
    "consectetur adipiscing elit",
    "sed do eiusmod tempor incididunt",
    "ut labore et dolore magna aliqua",
    "Ut enim ad minim veniam",
    "quis nostrud exercitation ullamco laboris",
    "nisi ut aliquip ex ea commodo consequat",
    "Duis aute irure dolor in reprehenderit",
    "in voluptate velit esse cillum dolore",
    "eu fugiat nulla pariatur",
    "Excepteur sint occaecat cupidatat non proident",
    "sunt in culpa qui officia deserunt mollit anim id est laborum",
    "Sed ut perspiciatis unde omnis iste natus error",
    "sit voluptatem accusantium doloremque",
    "laudantium, totam rem aperiam",
    "eaque ipsa quae ab illo inventore veritatis",
    "et quasi architecto beatae vitae dicta",
    "sunt explicabo. Nemo enim ipsam voluptatem",
    "quia voluptas sit aspernatur aut odit aut fugit",
    "sed quia consequuntur magni dolores eos",
    "qui ratione voluptatem sequi nesciunt",
    "Neque porro quisquam est",
    "qui dolorem ipsum quia dolor sit amet",
    "consectetur, adipisci velit",
    "sed quia non numquam eius modi tempora",
    "incidunt ut labore et dolore magnam aliquam",
    "quaerat voluptatem. Ut enim ad minima veniam",
    "quis nostrum exercitationem ullam corporis suscipit laboriosam",
    "nisi ut aliquid ex ea commodi consequatur",
    "Quis autem vel eum iure reprehenderit",
    "qui in ea voluptate velit esse quam nihil molestiae",
    "et iusto odio dignissimos ducimus",
    "qui blanditiis praesentium voluptatum deleniti",
    "atque corrupti quos dolores et quas molestias",
    "excepturi sint occaecati cupiditate non provident",
    "similique sunt in culpa qui officia deserunt",
    "mollitia animi, id est laborum et dolorum fuga",
    "Et harum quidem rerum facilis est et expedita distinctio",
    "Nam libero tempore, cum soluta nobis est eligendi",
    "optio cumque nihil impedit quo minus id quod maxime",
    "placeat facere possimus, omnis voluptas assumenda",
    "est, omnis dolor repellendus",
    "Temporibus autem quibusdam et aut officiis",
    "debitis aut rerum necessitatibus saepe eveniet",
    "ut et voluptates repudiandae sint et molestiae non recusandae",
    "Itaque earum rerum hic tenetur a sapiente",
    "delectus, ut aut reiciendis voluptatibus maiores",
    "alias consequatur aut perferendis doloribus asperiores repellat",
]

fake_data_literal = [
    "Dummy data 1",
    "Test data 2",
    "Placeholder 3",
    "Sample value 4",
    "Not real 5",
    "Mock data 6",
    "Faux value 7",
    "Artificial entry 8",
    "Fabricated info 9",
    "Simulated record 10",
    "Invalid content 11",
    "Imaginary entry 12",
    "Fictitious data 13",
    "Mock-up 14",
    "Pseudo value 15",
    "Non-authentic entry 16",
    "Placeholder text 17",
    "Faux record 18",
    "Artificial value 19",
    "Dummy content 20",
    "Test entry 21",
    "Fake information 22",
    "Invalid value 23",
    "Simulated data 24",
    "Imaginary content 25",
    "Not genuine 26",
    "Mock record 27",
    "Fabricated entry 28",
    "Placeholder info 29",
    "Faux entry 30",
    "Dummy value 31",
    "Test content 32",
    "Sample entry 33",
    "Non-authentic data 34",
    "Mock-up entry 35",
    "Pseudo content 36",
    "Simulated value 37",
    "Invalid data 38",
    "Faux information 39",
    "Imaginary value 40",
    "Placeholder record 41",
    "Fake content 42",
    "Artificial data 43",
    "Dummy record 44",
    "Test value 45",
    "Sample data 46",
    "Non-genuine entry 47",
    "Mock-up data 48",
    "Pseudo entry 49",
    "Simulated content 50",
]

first_name = [
    "Alex",
    "Alfonzo",
    "Amanda",
    "Amy",
    "Andrew",
    "Andy",
    "Angela",
    "Angie",
    "Anthony",
    "Ashley",
    "Barbara",
    "Becca",
    "Becky",
    "Betty",
    "Blake",
    "Brad",
    "Bradley",
    "Brian",
    "Carol",
    "Chris",
    "Christopher",
    "Cynthia",
    "Daniel",
    "Danny",
    "Dave",
    "David",
    "Deb",
    "Don",
    "Donald",
    "Donna",
    "Drew",
    "Dylan",
    "Ed",
    "Eddie",
    "Eduardo",
    "Edward",
    "Elizabeth",
    "Elliott",
    "Emily",
    "Eric",
    "Gene",
    "Hunter",
    "Isaiah",
    "Jacob",
    "Jaime",
    "Jake",
    "James",
    "Jamie",
    "Jeff",
    "Jeffrey",
    "Jen",
    "Jennifer",
    "Jessica",
    "John",
    "Jon",
    "Josh",
    "Joshua",
    "Karen",
    "Kelly",
    "Ken",
    "Kenneth",
    "Kevin",
    "Kim",
    "Kimberly",
    "Laura",
    "Lee",
    "Linda",
    "Lisa",
    "Liz",
    "Mandy",
    "Marcus",
    "Margaret",
    "Mark",
    "Mary",
    "Matt",
    "Matthew",
    "McKenzie",
    "Melissa",
    "Michael",
    "Michelle",
    "Mike",
    "Nancy",
    "Nell",
    "Nicholas",
    "Nick",
    "Owen",
    "Patricia",
    "Paul",
    "Peyton",
    "Quinn",
    "Rebecca",
    "Reese",
    "Richard",
    "Ricky",
    "Rob",
    "Robert",
    "Ron",
    "Ronald",
    "Ronnie",
    "Ryan",
    "Sam",
    "Samuel",
    "Sandra",
    "Sara",
    "Sarah",
    "Sharon",
    "Shellie",
    "Stephanie",
    "Stephen",
    "Steve",
    "Steven",
    "Susan",
    "Taylor",
    "Thomas",
    "Tim",
    "Timothy",
    "Tom",
    "Tony",
    "Uri",
    "Val",
    "Valerie",
    "Wynn",
    "Xi",
    "Yordan",
    "Zachary",
    "Zack",
    "Zoe",
]

last_name = [
    "Adams",
    "Allen",
    "Alvarez",
    "Anderson",
    "Bailey",
    "Baker",
    "Bennett",
    "Brooks",
    "Brown",
    "Campbell",
    "Carter",
    "Castillo",
    "Chavez",
    "Clark",
    "Collins",
    "Cook",
    "Cooper",
    "Cox",
    "Cruz",
    "Davis",
    "Diaz",
    "Edwards",
    "Evans",
    "Flores",
    "Foster",
    "Garcia",
    "Gomez",
    "Gonzalez",
    "Grand",
    "Gray",
    "Green",
    "Gutierrez",
    "Hall",
    "Harris",
    "Hernandez",
    "Hill",
    "Howard",
    "Hughes",
    "Jackson",
    "James",
    "Jimenez",
    "Johnson",
    "Jones",
    "Kelly",
    "Kim",
    "King",
    "Lee",
    "Lewis",
    "Long",
    "Lopez",
    "Martin",
    "Martinez",
    "Mendoza",
    "Miller",
    "Mitchell",
    "Moore",
    "Morales",
    "Morgan",
    "Morris",
    "Murphy",
    "Myers",
    "Nelson",
    "Nguyen",
    "Ortiz",
    "Parker",
    "Patel",
    "Perez",
    "Peterson",
    "Phillips",
    "Price",
    "Ramirez",
    "Ramos",
    "Reed",
    "Reyes",
    "Richardson",
    "Rivera",
    "Roberts",
    "Robinson",
    "Rodgers",
    "Rodriguez",
    "Rogers",
    "Ross",
    "Ruiz",
    "Sanchez",
    "Sanders",
    "Scott",
    "Smith",
    "Stewart",
    "Taylor",
    "Thomas",
    "Thompson",
    "Torres",
    "Turner",
    "Walker",
    "Ward",
    "Watson",
    "White",
    "Williams",
    "Wilson",
    "Wood",
    "Wright",
    "Young",
]

usernames = [
    "amartinez",
    "bnguyen",
    "csmith",
    "drodrigo",
    "eflynn",
    "fmunoz",
    "gstefani",
    "hsantiago",
    "imariposa",
    "jmiller",
    "knorthwood",
    "lpeterson",
]

departments = [
    "Accounting",
    "Administration",
    "Business Metrics",
    "Communications",
    "Customer Service",
    "Development",
    "Distribution",
    "Engineering",
    "Finance",
    "Human Resources",
    "Investor Relations",
    "IT",
    "Leadership",
    "Legal",
    "Management",
    "Marketing",
    "Operations",
    "Procurement",
    "Production",
    "Public Relations",
    "Purchasing",
    "Quality Assurance",
    "Research",
    "Sales",
    "Support",
    "Technology",
    "Training & Development",
]

job_titles = [
    "Account Manager",
    "Administrative Assistant",
    "Administrative Director",
    "Administrative Manager",
    "Administrative Supervisor",
    "Auditor 1",
    "Auditor 2",
    "Auditor 3",
    "Business Systems Analyst 1",
    "Business Systems Analyst 2",
    "Business Systems Analyst 3",
    "Client Relations Manager",
    "Consultant",
    "Content Manager",
    "Controller",
    "Finance Analyst 1",
    "Finance Analyst 2",
    "Finance Analyst 3",
    "Help Desk Associate",
    "Help Desk Coordinator",
    "Office Manager",
    "Product Manager",
    "Program Administrator",
    "Research Analyst 1",
    "Research Analyst 2",
    "Research Analyst 3",
    "Support Lead",
    "Support Technician",
    "Team Lead",
    "Technician 1",
    "Technician 2",
    "Technician 3",
]
